controller_manager:
  ros__parameters:
    update_rate: 300  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    #mecanum_drive_controller:
    #  type: tpc_mobile_mecanum_wheel_controller/TpcMobileMecanumController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    #imu_broadcaster:
    #  type: imu_sensor_broadcaster/IMUSensorBroadcaster

#    tm5_arm_controller:
#      type: joint_trajectory_controller/JointTrajectoryController

#mecanum_drive_controller:
#  ros__parameters:
#    fr_left_wheel_joint_name: "fr_left_wheel_joint"
#    fr_right_wheel_joint_name: "fr_right_wheel_joint"
#    rr_left_wheel_joint_name: "rr_left_wheel_joint"
#    rr_right_wheel_joint_name: "rr_right_wheel_joint"

#    wheel_radius: 0.03
#    wheel_distance:
#      width: 0.6
#      length: 0.575

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.7092
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.10

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Preserve turning radius when limiting speed/acceleration/jerk
    preserve_turning_radius: true

    # Publish limited velocity
    publish_cmd: true

    # Publish wheel data
    publish_wheel_data: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 2.0
    angular.z.min_acceleration: -2.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

#imu_broadcaster:
#  ros__parameters:
#    frame_id: imu_link
#    sensor_name: imu

#tm5_arm_controller:
#  ros__parameters:
#    joints:
#      - joint_1
#      - joint_2
#      - joint_3
#      - joint_4
#      - joint_5
#      - joint_6
#    interface_name: position

#    command_interfaces:
#      - position

#    state_interfaces:
#      - position
#      - velocity

#    state_publish_rate: 200.0 # Defaults to 50
#    action_monitor_rate: 20.0 # Defaults to 20

#    allow_partial_joints_goal: false # Defaults to false
#    open_loop_control: true
#    allow_integration_in_goal_trajectories: true
#    constraints:
#      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
#      goal_time: 0.0 # Defaults to 0.0 (start immediately)

