ekf_filter_node:
  ros__parameters:
    frequency: 30

    sensor_timeout: 0.1

    two_d_mode: true

    transform_time_offset: 0.0
    transform_timeout: 0.1

    print_diagnostics: true

    debug: false

    publish_tf: false
    publish_filtered_odom: true
    publish_acceleration: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: map

    odom0: /odom
    #odom0_config: [false, false, false,
    #               false, false, false,
    #               true,  true,  true,
    #               false, false, true,
    #               false, false, false]
    odom0_config: [true,  true,  false,
               false, false, true,
               true, false, false,
               false, false, true,
               false, false, false]
    odom0_queue_size: 20
    odom0_nodelay: false
    odom0_differential: false
    odom0_relative: false

    imu0: /imu/data
    #imu0_config: [false, false, false,
    #              false, false, false,
    #              true,  true,  false,
    #              true,  true,  true,
    #              false, false, false]
    imu0_config: [false, false, false,
              true,  true,  true,
              false, false, false,
              false, false, true,
              false, false, false]
    imu0_queue_size: 20
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true

    #laser0: /scan
    #laser0_config: [true,  true,  false,
    #                false, false, true,
    #                false, false, false,
    #                false, false, false,
    #                false, false, false]
    #laser0_queue_size: 10
    #laser0_nodelay: false
    #laser0_differential: false
    #laser0_relative: true

    use_control: false
