slam_toolbox:
  ros__parameters:
    use_sim_time: false

    odom_frame: "odom"
    base_frame: "base_footprint"
    map_frame: "map"

    scan_topic: "/scan"

    resolution: 0.01
    max_laser_range: 12.0
    minimum_time_interval: 0.2
    minimum_travel_distance: 0.1
    transform_timeout: 0.5

    enable_loop_closure: true
    loop_closure_scan_buffer_size: 200
    loop_closure_match_threshold: 0.6

    solver_plugin: solver_plugins::CeresSolver
