# Configuration file for EtherCAT EBus Coupler (with DOx8 DIx8)
vendor_id: 0x00000794
product_id: 0x01010101
#assign_activate: 0x0300  # DC Synch register
#auto_fault_reset: true  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"

#sdo:  # sdo data to be transferred at drive startup
#  - {index: 0x60C2, sub_index: 1, type: int8, value: 10} # Set interpolation time for cyclic modes to 10 ms
#  - {index: 0x60C2, sub_index: 2, type: int8, value: -3} # Set base 10-3s
  #- {index: 0x6098, sub_index: 0, type: int8, value: 35}
rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1600
    channels:
      - {index: 0x7000, sub_index: 1, type: uint8, command_interface: d_output, default: 1}  # Output

tpdo:  # TxPDO = transmit PDO Mapping
  - index: 0x1a00
    channels:
      - {index: 0x6000, sub_index: 1, type: uint8, state_interface: d_input}  # Input

sm:  # Sync Manager
  - {index: 0, type: output, pdo: rpdo, watchdog: enable}
  - {index: 1, type: input, pdo: tpdo, watchdog: disable}

