# Configuration file for EtherCAT QSI Safety Monitor Module
vendor_id: 0x00000794
product_id: 0x01101e00
#assign_activate: 0x0300  # DC Synch register
#auto_fault_reset: true  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"

#sdo:  # sdo data to be transferred at drive startup
#  - {index: 0x60C2, sub_index: 1, type: int8, value: 10} # Set interpolation time for cyclic modes to 10 ms
#  - {index: 0x60C2, sub_index: 2, type: int8, value: -3} # Set base 10-3s
  #- {index: 0x6098, sub_index: 0, type: int8, value: 35}
rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1600
    channels:
      - {index: 0x8000, sub_index: 0, type: uint16, default: 0}  # Control
      - {index: 0x8000, sub_index: 2, type: uint16, default: 0}  # Control Ex
      - {index: 0x8050, sub_index: 2, type: uint32}  # TCP Speed (mm/sec)

tpdo:  # TxPDO = transmit PDO Mapping
  - index: 0x1a00
    channels:
      - {index: 0x9000, sub_index: 0, type: uint16}  # Status
      - {index: 0x9000, sub_index: 2, type: uint16}  # Status Ex
      - {index: 0x8050, sub_index: 4, type: uint16}  # Fault Data Offset
      - {index: 0x8050, sub_index: 5, type: uint8}  # Fault Data Type
      - {index: 0x8050, sub_index: 6, type: uint32}  # Fault Data Value


sm:  # Sync Manager
  - {index: 0, type: output, pdo: rpdo, watchdog: enable}
  - {index: 1, type: input, pdo: tpdo, watchdog: disable}

