# Configuration file for Maxon EPOS3 drive
vendor_id: 0x00000794
product_id: 0x01021e00
assign_activate: 0x0300  # DC Synch register
auto_fault_reset: true  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"


rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1600
    channels:
      - {index: 0x6040, sub_index: 0, type: uint16, default: 32768}  # Control word
      - {index: 0x6060, sub_index: 0, type: int8}  # Mode of operation
      - {index: 0x607a, sub_index: 0, type: int32, command_interface: position, factor: 95917.62554822, offset: 0}  # Target position
tpdo:  # TxPDO = transmit PDO Mapping
  - index: 0x1a00
    channels:
      - {index: 0x603f, sub_index: 0, type: uint16}  # Error code
      - {index: 0x6041, sub_index: 0, type: uint16}  # Statusword
      - {index: 0x6061, sub_index: 0, type: int8}  # Mode of operation display
      - {index: 0x6064, sub_index: 0, type: int32, state_interface: position, factor: 0.000010426, offset: 0}  # Position actual value
      - {index: 0x60f4, sub_index: 0, type: int32}  # Following error actual value
